name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Buildozer Environment (Download SDK/NDK)
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi
          timeout 10m buildozer android debug || true

      - name: Accept Android SDK Licenses
        run: |
          SDK_MANAGER_PATH="\$HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager"
          if [ -f "\$SDK_MANAGER_PATH" ]; then
            yes | "\$SDK_MANAGER_PATH" --licenses
          else
            echo "ERROR: sdkmanager not found"
            exit 1
          fi

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-file
          path: bin/*.apk
